social:
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
  - name: Home 
    link: https://www.scumtb.cn
    icon: ri:home-7-line
    color: '#1296db'
  - name: Bilibili 
    link: https://space.bilibili.com/639433048
    icon: ri:bilibili-line
    color: '#FF8EB3'  
  - name: Music
    link: https://music.163.com/#/user/home?id=7800557453
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: Steam
    link: https://steamcommunity.com/id/ScumTB
    icon: ri:steam-fill
    color: '#004986' 
  - name: Twitter
    link: https://twitter.com/Scum33299664
    icon: ri:twitter-line
    color: '#1da1f2'


reward:
  enable: false


albums:
  enable: true

encrypt:
  enable:true
      
head:
  css:
    aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css
  js:
    defer:
      aplayer: https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js
      loadAplayer: /js/load-aplayer.js

say:
  enable: true
  # https://developer.hitokoto.cn/sentence/
  api: /data/sentences.json 
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn/?c=a 
say-content:
  color: white



favicon: /1.svg


sidebar:
  src: /js/sidebar.js
  bg_image: https://cdn.staticaly.com/gh/ScumTB/blogpictures@master/test/000.png 
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

mourn:
  enable: true
  days:
    - 4-4
    - 5-2
    - 12-13


# å…³é—­ highlight
highlight:
  enable: false
# å¯ç”¨ prism
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''




girls:
  enable: true


pjax:
  enable: true



banner:
  enable: true
  title: ScumTBçš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
avatar:
  enable: true
  url: /images/th.jpeg
  rounded: true
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä½ é¸¡å·´è°å•Š 

footer:
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2022-10-29T00:00:00'
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: record
      path: /diary/
      icon: ri:edit-2-line
    - type: pictures
      path: /tags/
      icon: ri:book-2-line
   # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: ä½ çŒœ
  custom:
    title: About
    path: https://blog.scumtb.cn/about/
    icon: ri:settings-line

pages:
  - name: girls 
    url: /girls/
    icon: ri:women-line
    color: hotpink
  - name: pixv
    url: /pixiv/
    icon: ri:parking-line
    color: '#0074AA'
  - name: albums
    url: /albums/
    icon: ri:camera-line 
    color: '#d4237a' 
